### ISSUE TITLE
_get_kind_list raise 404 Error when retrieving subkinds

### ISSUE THREAD

**Issue by missing1984** [splunk/splunk-sdk-python#101]
SDK 1.3.1

Error trace
```
Traceback (most recent call last):
  File "sdktest.py", line 88, in <module>
    inputs(service)
  File "sdktest.py", line 41, in inputs
    for i in inputs:
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2528, in __iter__
    for item in self.iter(**kwargs):
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2552, in iter
    for item in self.list(**kwargs):
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2455, in list
    kinds = self.kinds
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2357, in kinds
    return self._get_kind_list()
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2346, in _get_kind_list
    subkinds = self._get_kind_list(subpath + [entry.title])
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2346, in _get_kind_list
    subkinds = self._get_kind_list(subpath + [entry.title])
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 2334, in _get_kind_list
    response = self.get('/'.join(subpath))
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 1611, in get
    return super(Collection, self).get(name, owner, app, sharing, **query)
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/client.py", line 709, in get
    **query)
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/binding.py", line 241, in wrapper
    return request_fun(self, *args, **kwargs)
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/binding.py", line 63, in new_f
    val = f(*args, **kwargs)
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/binding.py", line 586, in get
    response = self.http.get(path, self._auth_headers, **query)
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/binding.py", line 1057, in get
    return self.request(url, { 'method': "GET", 'headers': headers })
  File "/Users/michael/workspace/stash/app-aws/package/bin/splunklib/binding.py", line 1112, in request
    raise HTTPError(response)
splunklib.binding.HTTPError: HTTP 404 Not Found -- Not Found

```

```python
    def _get_kind_list(self, subpath=None):
        if subpath is None:
            subpath = []

        kinds = []
        response = self.get('/'.join(subpath))  -<< self.get will always encode slash that failed this request.
```

**Comment by shakeelmohamed** [comment]
Thanks @missing1984 we'll look into this

**Comment by shakeelmohamed** [comment]
Sent you an email asking for more info

**Comment by itay** [comment]
This is no longer an issue.
