### ISSUE TITLE
test_binding

### ISSUE THREAD

**Issue by rhaarm** [splunk/splunk-sdk-python#107]
Hi,

I just wanted to check if these were known issues, I get these no matter which server I point them at. The assertEqual is looking for a Bad Request (400) but a Server Internal Error (500) is returned.

```
$ python test_binding.py
...............................................EEEEE
======================================================================
ERROR: test_create_user (__main__.TestUserManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binding.py", line 210, in setUp
    self.assertEqual(e.status, 400)
AssertionError: 500 != 400

======================================================================
ERROR: test_post_with_body_behaves (__main__.TestUserManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binding.py", line 210, in setUp
    self.assertEqual(e.status, 400)
AssertionError: 500 != 400

======================================================================
ERROR: test_post_with_get_arguments_to_receivers_stream (__main__.TestUserManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binding.py", line 210, in setUp
    self.assertEqual(e.status, 400)
AssertionError: 500 != 400

======================================================================
ERROR: test_update_user (__main__.TestUserManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binding.py", line 210, in setUp
    self.assertEqual(e.status, 400)
AssertionError: 500 != 400

======================================================================
ERROR: test_user_without_role_fails (__main__.TestUserManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_binding.py", line 210, in setUp
    self.assertEqual(e.status, 400)
AssertionError: 500 != 400

----------------------------------------------------------------------
Ran 52 tests in 9.296s

FAILED (errors=5)
```

**Comment by rhaarm** [comment]
I have decided to close this as I am finding more test errors and will be either sending an email with all listed or creating a new issues chain concerning all found errors.
