### ISSUE TITLE
Key Error in Python Splunk SDK while accessing KV store

### ISSUE THREAD

**Issue by Manikandankasi01** [splunk/splunk-sdk-python#256]
Hi,

I'm getting Key Error while accessing splunk kv store using splunk python sdk.
Python Version: 2.7
Splunk sdk version : 1.6.6
OS: Windows 7 & 10

```python
import sys, json
from splunklib.client import connect 
import getpass
 
 
 def main():
     #Getting Splunk access details from User
     hostname = raw_input("Enter Splunk Hostname/IP: ")
     splunkUser = raw_input("Enter Splunk Admin Username: ")
     splunkPassword = getpass.getpass("Enter Splunk Admin Password: ")
     HOST = hostname
     PORT = 8089
     USERNAME = splunkUser
     PASSWORD = splunkPassword
     #Connecting splunk server
     splunk_service = connect(host=HOST,port=PORT,username=USERNAME,password=PASSWORD)
     print("Splunk connection succeed !!!!")
     splunk_service.namespace['owner'] = 'Nobody'
     collection_name="test"
     collection=splunk_service.kvstore[collection_name]
 
     if collection_name in splunk_service.kvstore:
         print("{} Already exist !!!".format(collection_name))
     else:
         splunk_service.kvstore.create(collection_name)
     
     #Adding data to KV store
     collection.data.insert(json.dumps({"ID":"123","sId":1234,"Tech":"text"}))
 
     #Retriving data from kv store
     kv_data=json.dumps(collection.data.query(),indent=1)
     print(kv_data)
 
 if __name__ == '__main__':
     main()
     
 ```

Error Details:
Traceback (most recent call last):
File "kv_store_opps.py", line 36, in 
main()
File "kv_store_opps.py", line 21, in main
collection=splunk_service.kvstore[collection_name]
File "C:\Python27\lib\site-packages\splunklib\client.py", line 1243, in getitem
raise KeyError(key)
KeyError: UrlEncoded('test')

Any help on this much appreciated.

Thanks,
Mani

**Comment by shakeelmohamed** [comment]
Hi @Manikandankasi01,

You're seeing this `KeyError` because the `collection_name` doesn't exist in kvstore.
You can fix this by wrapping this line in a try/except block.

```python
collection=splunk_service.kvstore[collection_name]
```

I would refactor your code like so:

```python
try:
    collection=splunk_service.kvstore[collection_name]
    print("{} Already exist !!!".format(collection_name))
except KeyError:
    collection=splunk_service.kvstore.create(collection_name)
```

Overall diff would become:

```diff
import sys, json
from splunklib.client import connect 
import getpass
 
 
 def main():
     #Getting Splunk access details from User
     hostname = raw_input("Enter Splunk Hostname/IP: ")
     splunkUser = raw_input("Enter Splunk Admin Username: ")
     splunkPassword = getpass.getpass("Enter Splunk Admin Password: ")
     HOST = hostname
     PORT = 8089
     USERNAME = splunkUser
     PASSWORD = splunkPassword
     #Connecting splunk server
     splunk_service = connect(host=HOST,port=PORT,username=USERNAME,password=PASSWORD)
     print("Splunk connection succeed !!!!")
     splunk_service.namespace['owner'] = 'Nobody'
     collection_name="test"
-      collection=splunk_service.kvstore[collection_name]
-  
-      if collection_name in splunk_service.kvstore:
-          print("{} Already exist !!!".format(collection_name))
-      else:
-          splunk_service.kvstore.create(collection_name)
+
+     try:
+         collection=splunk_service.kvstore[collection_name]
+         print("{} Already exist !!!".format(collection_name))
+     except KeyError:
+         collection=splunk_service.kvstore.create(collection_name)
     
     #Adding data to KV store
     collection.data.insert(json.dumps({"ID":"123","sId":1234,"Tech":"text"}))
 
     #Retriving data from kv store
     kv_data=json.dumps(collection.data.query(),indent=1)
     print(kv_data)
 
 if __name__ == '__main__':
     main()
```

**Comment by Manikandankasi01** [comment]
Thanks shakeelmohamed. its worked !!!.

**Comment by souravsharma6633** [comment]
Hi,
I am facing the same KeyError issue. But, I already have the collection defined in collections.conf file. I am able to CRUD the collection from the rest API but custom command is giving this KeyError.
Urgent help is needed.

Thanks,
Sourav
