### ISSUE TITLE
API Endpoint breaks on output_mode="Json"

### ISSUE THREAD

**Issue by christoffertoft** [splunk/splunk-sdk-python#357]
**Describe the bug**
When calling service.apps.list() with output_mode="json", Etree cannot parse the results:

**To Reproduce**
Initialize a connection to your Splunk Search Head:
```python
s = splunklib.client.connect(host=myhost ... )
s.apps.list(output_mode="json")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/splunklib/client.py", line 1479, in list
    return list(self.iter(count=count, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/splunklib/client.py", line 1439, in iter
    items = self._load_list(response)
  File "/usr/local/lib/python3.6/site-packages/splunklib/client.py", line 1345, in _load_list
    entries = _load_atom_entries(response)
  File "/usr/local/lib/python3.6/site-packages/splunklib/client.py", line 208, in _load_atom_entries
    r = _load_atom(response)
  File "/usr/local/lib/python3.6/site-packages/splunklib/client.py", line 203, in _load_atom
    .decode('utf-8', 'xmlcharrefreplace'), match)
  File "/usr/local/lib/python3.6/site-packages/splunklib/data.py", line 85, in load
    root = XML(text)
  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

**Expected behavior**
Should return a list of the Application objects but json formed, like a call to `s.apps.list()` would:
>>> s.apps.list()
[<splunklib.client.Application object at 0x7f0f00b7ff60>, <splunklib.client.Application object at 0x7f0f00b7feb8>, <splunklib.client.Application object at 0x7f0f00b7fef0>, <splunklib.client.Application object at 0x7f0f00b7fe48>, <splunklib.client.Application object at 0x7f0f00b7fe10>, <splunklib.client.Application object at 0x7f0f00b7fdd8>, <splunklib.client.Application object at 0x7f0f00be7a20>, <splunklib.client.Application object at 0x7f0f00be7a58>]

**Logs or Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Splunk **
- Version: [ 8.0.5]
- OS: [ Ubuntu 20.04.1]
- Deployment: [. single-instance]

**SDK **
splunk-sdk          1.6.14
splunklib           1.0.0
Python 3.8.5

**Comment by ncanumalla-splunk** [comment]
@christoffertoft This SDK does not support Json output_mode but only XML output. 
Can you please provide more details where you expect Json results and why you used the output_mode as Json?
