### ISSUE TITLE
search.py verbose flag issue

### ISSUE THREAD

**Issue by mrkprdo** [splunk/splunk-sdk-python#373]
I do understand there are still ongoing works to migrate python2 to python3
Just wanted to document `example/search.py`

```bash
Traceback (most recent call last):
  File "splunk-sdk-python\examples\search.py", line 118, in <module>
    main(sys.argv[1:])
  File "splunk-sdk-python\examples\search.py", line 96, in main
    if verbose > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

This can be interpreted to:
```python
if bool(verbose) > 0:
    ...
```
 [bool()](https://docs.python.org/3.8/library/functions.html?highlight=bool#bool) defninition

**Comment by ashah-splunk** [comment]
Hi @mrkprdo , we tried executing the example mentioned and it worked fine in both the scenarios with and without the verbose flag for both python2 and python3 . 
We would request you to use the latest version of the SDK and let us know if you face the same error. Thanks
