### ISSUE TITLE
how to resolve connecting to splunk via phython?

### ISSUE THREAD

**Issue by fishert123** [splunk/splunk-sdk-python#489]
I got the same error 
Traceback (most recent call last):
  File "./HelloWorld.py", line 19, in <module>
    service = client.connect(host='splunk.xxxx.edu', port=443, username='user1', password=pswd)
  File "/usr/lib/python2.7/site-packages/splunklib/client.py", line 331, in connect
    s.login()
  File "/usr/lib/python2.7/site-packages/splunklib/binding.py", line 886, in login
    session = XML(body).findtext("./sessionKey")
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

I came across a reply here https://github.com/splunk/splunk-sdk-python/issues/311 
The response body isn't xml, it's html:
b'<!doctype html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta http-equiv="refresh" content="1;url=https://server/en-US/services/auth/login"><title>303 See Other</title></head><body><h1>See Other</h1><p>The resource has moved temporarily <a href="https://server/en-US/services/auth/login">here</a>.</p></body></html>\r\n'

How to resolve this ?  Can I force python script to accept html instead of xml ?

thanks !!

**Comment by fishert123** [comment]
thanks so much !!

**Comment by ncanumalla-splunk** [comment]
@fishert123 Can you confirm if this issue is resolved for you and it can be closed?

**Comment by fishert123** [comment]
Yes, it is working.  You can close it.
Thanks so much .
