### ISSUE TITLE
 python 3.11 / 3.12 | ModuleNotFoundError: No module named 'splunklib.six.moves'

### ISSUE THREAD

**Issue by exenin** [splunk/splunk-sdk-python#529]
**Describe the bug**

Breaks when installing this library using python 3.11 / 3.12

`#0 1.244   Running command git clone --filter=blob:none --quiet https://github.com/splunk/splunk-sdk-python.git /tmp/pip-req-build-6b1cibcd                                                                  
#0 3.899   Resolved https://github.com/splunk/splunk-sdk-python.git to commit e44135872675d8f5450b7eef990735b233477b27                                                                                       
#0 3.906   Installing build dependencies: started
#0 8.658   Installing build dependencies: finished with status 'done'
#0 8.659   Getting requirements to build wheel: started
#0 9.055   Getting requirements to build wheel: finished with status 'error'
#0 9.071   error: subprocess-exited-with-error
#0 9.071   
#0 9.071   × Getting requirements to build wheel did not run successfully.
#0 9.071   │ exit code: 1
#0 9.071   ╰─> [23 lines of output]
#0 9.071       Traceback (most recent call last):
#0 9.071         File "/opt/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 9.071           main()
#0 9.071         File "/opt/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 9.071           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 9.071                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 9.071         File "/opt/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#0 9.071           return hook(config_settings)
#0 9.071                  ^^^^^^^^^^^^^^^^^^^^^
#0 9.071         File "/tmp/pip-build-env-n1rxte_x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
#0 9.071           return self._get_build_requires(config_settings, requirements=['wheel'])
#0 9.071                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 9.071         File "/tmp/pip-build-env-n1rxte_x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
#0 9.071           self.run_setup()
#0 9.071         File "/tmp/pip-build-env-n1rxte_x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 488, in run_setup
#0 9.071           self).run_setup(setup_script=setup_script)
#0 9.071                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 9.071         File "/tmp/pip-build-env-n1rxte_x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 338, in run_setup
#0 9.071           exec(code, locals())
#0 9.071         File "<string>", line 22, in <module>
#0 9.071         File "/tmp/pip-req-build-6b1cibcd/splunklib/__init__.py", line 18, in <module>
#0 9.071           from splunklib.six.moves import map
#0 9.071       ModuleNotFoundError: No module named 'splunklib.six.moves'
#0 9.071       [end of output]
#0 9.071   
#0 9.071   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 9.075 error: subprocess-exited-with-error
#0 9.075 
#0 9.075 × Getting requirements to build wheel did not run successfully.
#0 9.075 │ exit code: 1
#0 9.075 ╰─> See above for output.
#0 9.075 
#0 9.075 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1
`

**To Reproduce**

install using python3.11/3.12

**Comment by ashah-splunk** [comment]
@exenin we are not able to reproduce the issue by executing the command `git clone --filter=blob:none --quiet https://github.com/splunk/splunk-sdk-python.git /tmp/pip-req-build-6b1cibcd` (shared above) in both python3.11 and 3.12.  Please let us know if any more steps are required to reproduce the issue

**Comment by ashah-splunk** [comment]
Closing the Issue as we haven't heard back. 
@exenin please reopen the Issue if you are still facing the issue.
