### ISSUE TITLE
Receiving SSL error 

### ISSUE THREAD

**Issue by httpstergeek** [splunk/splunk-sdk-python#98]
Receiving SSL error when connecting to Splunk instance over port 80.  BigIP Listens on port 80 forwards to splunk instance on 8089.  I am able to connect if I use urllib, urllib2.

Traceback (most recent call last):
  File "info.py", line 32, in <module>
    service = client.connect(**opts.kwargs)
  File "../splunklib/client.py", line 305, in connect
    return Service(**kwargs).login()
  File "../splunklib/binding.py", line 762, in login
    password=self.password)
  File "../splunklib/binding.py", line 1091, in post
    return self.request(url, message)
  File "../splunklib/binding.py", line 1108, in request
    response = self.handler(url, message, **kwargs)
  File "../splunklib/binding.py", line 1230, in request
    connection.request(method, path, body, head)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1198, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 392, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 148, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by shakeelmohamed** [comment]
Hi @httpstergeek,

Thanks for the bug report, we will look into this.

**Comment by httpstergeek** [comment]
Hi @shakeelmohamed,

I am closing this bug.  After further investigation I believe this error is caused by a misconfigured virtual server.

**Comment by glennblock** [comment]
Thanks @httpstergeek. On a diff note, love your github avatar :-)
